### ISSUE TITLE
Sample: "logout" button has strange behavior

### ISSUE THREAD

**Issue by Zhuinden** [isaac-udy/Enro#3]
![image](https://user-images.githubusercontent.com/11718392/80297964-98f95300-8788-11ea-83ad-4b4129d42a92.png)

**Comment by Zhuinden** [comment]
> `navigation.forward(UserKey(userId = navigation.key.userId.repeat(2)))`

Welp, this is expected, nevermind me

**Comment by isaac-udy** [comment]
Haha, this was for testing - I'll change it back to the correct behaviour.
