### ISSUE TITLE
Incompatible with Hilt

### ISSUE THREAD

**Issue by Cotel** [isaac-udy/Enro#9]
Hi!

I'd like to use this library in my project but it seems to be incompatible with Hilt. Just by adding the dependency kapt starts to fail with `cannot access GeneratedComponentManagerHolder`.

I've seen in the `modularised-example` that there is an `EnroHilt` plugin but adding it to the navigation controller doesn't change anything for me.

I'm currently using:
* Hilt version: 1.0.0-alpha02
* Enro version: 1.2.4

**Comment by isaac-udy** [comment]
Supporting Hilt is something that I've very keen on, so this is an important issue for me. 

Do you mind sharing your build.gradle file with me (or your whole project as a zip)? Or possibly creating an example project that can reproduce this issue?  I've created a super simple app with just Enro and Hilt dependencies and I can't reproduce. 


Troubleshooting questions: 
- Are you using multiple modules? 
- Have you tried cleaning and re-building? 
- Are you using the Hilt gradle plugin as well? 
- Are you using all of the hilt dependencies? These are: 
```
    implementation 'com.google.dagger:hilt-android:2.29-alpha'
    implementation 'androidx.hilt:hilt-lifecycle-viewmodel:1.0.0-alpha02'
    kapt 'androidx.hilt:hilt-compiler:1.0.0-alpha02'
    kapt 'com.google.dagger:hilt-android-compiler:2.29-alpha'
```

**Comment by isaac-udy** [comment]
It's worth noting that the "GeneratedComponentManagerHolder" is an interface belonging to the 'com.google.dagger:hilt-android:2.29-alpha' dependency - is it possible that dependency is missing somewhere?

**Comment by Cotel** [comment]
I'll try to reproduce the error in a smaller project.

Regarding your questions:

* The project is just one module
* I've tried cleaning the project, removing the `@NavigationComponent` annotation from Application, etc.
* Yes, I'm using the Hilt gradle plugin.
* The gradle dependencies I am using are these:

```
def version_hilt = "2.28-alpha"
def version_androidx_hilt = "1.0.0-alpha02"

implementation "com.google.dagger:hilt-android:$version_hilt"                   
implementation "androidx.hilt:hilt-lifecycle-viewmodel:$version_androidx_hilt"  
kapt "com.google.dagger:hilt-android-compiler:$version_hilt"                    
kapt "androidx.hilt:hilt-compiler:$version_androidx_hilt"
                       
testImplementation "com.google.dagger:hilt-android-testing:$version_hilt"       
kaptTest "com.google.dagger:hilt-android-compiler:$version_hilt"
                
androidTestImplementation "com.google.dagger:hilt-android-testing:$version_hilt"
kaptAndroidTest "com.google.dagger:hilt-android-compiler:$version_hilt"         
```

> It's worth noting that the "GeneratedComponentManagerHolder" is an interface belonging to the 'com.google.dagger:hilt-android:2.29-alpha' dependency - is it possible that dependency is missing somewhere?

I am going to try update to 2.29 to see if that version solves this issue.

**Comment by Cotel** [comment]
Updating to Hilt 2.29 solves the problem 👌

**Comment by isaac-udy** [comment]
@Cotel I'm very glad to hear that! Thanks for reporting the issue, please let me know if you have any other trouble (or any feature requests!).
